### ISSUE TITLE
macOS 10.15.7: corrupt display of psautohinted CFF2 font

### ISSUE THREAD

**Issue by madig** [adobe-type-tools/psautohint#287] opened 2020-12-23 09:47 UTC
Open the VF in https://download.gnome.org/sources/cantarell-fonts/0.301/cantarell-fonts-0.301.tar.xz in Fontbook and see that various glyphs like "p" won't display. It works if you leave out the autohinting.

Source repo: https://gitlab.gnome.org/GNOME/cantarell-fonts

For testing, you can run (after following the build instructions up to before calling meson):

`python scripts/make-variable-font.py src/Cantarell.designspace src/Cantarell.stylespace echo /tmp/Cantarell-VF.otf`

for no autohinting, and

`python scripts/make-variable-font.py src/Cantarell.designspace src/Cantarell.stylespace psautohint /tmp/Cantarell-VF.otf`

for autohinting.

**Comment by iterumllc** [comment] 2022-04-01 11:30
I've confirmed the effect with the supplied font and that hinting with the current pyport prototype doesn't have the problem (at least with the glyphs displayed by default in Font Book).

**Comment by madig** [comment] 2022-04-01 15:07
That's interesting to know! Is this port public? Is there a roadmap?

**Comment by skef** [comment] 2022-04-01 17:59
It's floating around but there's still work to be done on things like overlap handling. No official roadmap at present.

**Comment by skef** [comment] 2023-08-14 21:49
We eventually saw some of these problems in our production but it appeared to be caused by the combination of hinting and subroutinization. In any case we filed a bug with Apple and they fixed it. We're not sure what releases they backported the fix to.

otfautohint, a python port of psautohint now merged (but not yet released) into afdko, has the code for properly hinting variable cff2 fonts.

**Closed by skef** 2023-08-14 21:49 UTC
Labels: high priority
