### ISSUE TITLE
Compatible hinting (-r) produces corrupt hinting

### ISSUE THREAD

**Issue by madig** [adobe-type-tools/psautohint#189] opened 2019-09-06 19:56 UTC
1. Unzip [Cantarell-n.zip](https://github.com/adobe-type-tools/psautohint/files/3585503/Cantarell-n.zip)
2. `fontmake -m Cantarell.designspace -o otf-interpolatable`
3. `cd master_otf_interpolatable && psautohint -r Cantarell-Regular.otf Cantarell-Bold.otf Cantarell-Light.otf`
4. `ftgrid 16 Cantarell-Regular.otf` from the freetype2-demos package

The following happens on all glyphs that consist of multiple contours when using `-r`, it does not happen when not hinting compatibly:

![grafik](https://user-images.githubusercontent.com/380829/64456475-33b4fc80-d0e8-11e9-9162-648d8c3e03ed.png)

(psautohint 2.0.0a1, FreeType git master 3de1b8d0b0983cf49a187a4227e7950395a3b08f)

**Comment by khaledhosny** [comment] 2019-09-06 20:31
AFAIK, psautohint does not behave well with overlapping outlines in general (see #40).

**Comment by madig** [comment] 2019-09-06 20:57
Oh, ok. This also happens when I remove overlaps: [Cantarell-n-no-overlaps.zip](https://github.com/adobe-type-tools/psautohint/files/3585701/Cantarell-n-no-overlaps.zip)

**Comment by readroberts** [comment] 2019-10-24 19:57
@madig Please try and reproduce this, with the latest version on the master branch. I cannot reproduce this now. I suspect that this happened before I added code to remove hints that are invalid any of the region fonts.

**Comment by madig** [comment] 2019-10-25 19:54
Can still reproduce, using `psautohint-2.0.0a3.dev1+g4c503e7`: [Cantarell-VF.zip](https://github.com/adobe-type-tools/psautohint/files/3773577/Cantarell-VF.zip). Also note the accented versions of `/n` and `/eng`.

**Comment by readroberts** [comment] 2019-12-03 21:56
Fixed in PR 205

**Comment by madig** [comment] 2019-12-03 23:11
Can confirm that "n" looks good now, but the hinted font now has other weird glitches that don't exist in the statics.

![Bildschirmfoto vom 2019-12-03 23-05-13](https://user-images.githubusercontent.com/380829/70097540-8f2c5300-1621-11ea-8212-b2c46b84210c.png)

[Cantarell-VF.zip](https://github.com/adobe-type-tools/psautohint/files/3919126/Cantarell-VF.zip)

Also, the space character is gone when used in Firefox and Chrome?! I see a hintmask in "space" :o

**Comment by josh-hadley** [comment] 2019-12-04 18:09
> Can confirm that "n" looks good now, but the hinted font now has other weird glitches that don't exist in the statics.
>the glitch is nicely visible on https://www.axis-praxis.org/ when sliding through wght, watch glyphs with round tops. Some kind of FreeType-specific rounding issue or off-by-one?

I see what you mean about the other weird glitches. We'll investigate this more and try to determine exactly what's going on. It appears to me that it's only happening on ~x-height overshoots (not uppercase or figures), which makes me think it's probably the hints and not FreeType. Happens across a pretty wide range of sizes and all across the weight axis.

> Also, the space character is gone when used in Firefox and Chrome?! I see a hintmask in "space" :o

I could not substantiate this. TTX dump shows:
```
        <CharString name="space">
        </CharString>
```
i.e. no hints, no paths/subrs. Where did you see `hintmask` in "space"?

**Comment by readroberts** [comment] 2019-12-04 20:54
I have to be out for the rest of the day, but will look at this tomorrow. If the problem is with overshoots, then perhaps there is a problem with the font-level alignment zones, aka BlueValues.

**Comment by madig** [comment] 2019-12-04 21:54
> i.e. no hints, no paths/subrs. Where did you see hintmask in "space"?

Oops sorry, I didn't look closely and looked at the `sterling` after it. Thanks for looking into this!

**Comment by readroberts** [comment] 2019-12-10 01:12
The problem is that the x-height alignment zone isn't always catching the top of the 'o'. You can see this clearly in Axis-Praxis and in FontView at 9 points at Weight = 788, while the zone does catch the top of the 'o' at Weight = 787. At Weight=787, the BlueValue zone is [489.492, 499.492], while the hstem is[ 360 499]. The top edge of the hstem is in the alignment zone.  At Weight=788, the BlueValue zone is [489.531, 499.531], while the hstem is [ 360 500]. The top edge of the hint is NOT in the alignment zone, and the top edge of the 'o'  is not forced to the top of the alignment zone. If I change the BlueValue from [489.531, 499.531] to [489.531, 500], then the alignment zone does catch the hint.

I speculate that the reason why this is a problem in Axis-Praxis and FontView, but is not a problem in FontCTS,  is that FontCTS rounds the BlueValues, and FreeType doesn't. I will ask my co-workers, who are more familiar with the code, to check this in FontViewCTS.

A way to fix this in the font is to set BlueFuzz to 1, which adds one character space unit to the alignment zone. See p 51, the Adobe Type 1 Specification.

It is not immediately clear to me  that rounding the blended BlueValues will always work. We need to think about this.

It also interesting to note that at Weight=787, the top edge of the top hint rounds to 499, but the top of the 'o' is still rounding to 500, rather than 499. 

Testing notes:
I used Axis Praxis with the latest Cantarell-VF.otf from above, and looked for the closest two Weight values that would/would not catch the top hstem. I the used 'tx -cff -std+b -U <weight value> Cantarell-VF.otf Cantarell-<weight value>.otf  to make instance fonts at the two weight values, and checked that I did see the expected behavior in FontView. (Note: this command actually makes a CFF instance only, but it turns out that FontView happily opens a CFF font if you give it an '.otf' extension). I used 'tx -t1' and 'detype1' to make an editable text version, then went the other way with 'type1' and 'tx -cff'. For the instance at 788, the problem when away if I see the top of the alignment zone to 500, or if I set BlueFuzz to 1. (another note - if you open a font with FontView, it seems to cache some metrics: if I edit the font and only close the window and re-open  the font file after editing it, the behavior does not change. I had to actually quit FontView, and then re-open the font file).

**Comment by josh-hadley** [comment] 2019-12-10 22:33
Closing this out; original issue was addressed and secondary issue ('bouncing' glyphs) is not directly caused by `psautohint`.

**Closed by josh-hadley** 2019-12-10 22:33 UTC
Labels: CFF2, high priority

**Comment by madig** [comment] 2019-12-12 22:03
For the record: I tracked down the space-glyphs-have-no-space problem to a FreeType regression introduced after 2.10.1: https://lists.nongnu.org/archive/html/freetype-devel/2019-12/msg00000.html
