### ISSUE TITLE
--print-dflt-fddict results in error

### ISSUE THREAD

**Issue by kontur** [adobe-type-tools/psautohint#222] opened 2020-01-14 08:38 UTC
It seems any font I try the `--print-dftl-fddict` param on I get an error of `ERROR: 'NoneType' object is not subscriptable`.

I haven't debugged this any further, but since three different font files I tried all resulted in this categorical error there seems to be something amiss with the values to report not getting passed.

**Comment by kontur** [comment] 2020-01-14 15:26
Firstly, this [return](https://github.com/adobe-type-tools/psautohint/blob/master/python/psautohint/autohint.py#L532) seems to prevent returning a `fontinfo_list`, which then bubbles up and ultimately fails the call.

Is calling with `--print-dftl-fddict` intended to end execution after the print of that information? If so, then it needs to exit more gracefully.

Secondly, this [try with silent pass](https://github.com/adobe-type-tools/psautohint/blob/master/python/psautohint/autohint.py#L423) is the reason there is no actual output, despite the passed in  `fontInfoString` actually having content. The whole `printFontInfo` seems pretty funky... a string representation of FDDict is passed to it, then some keys are matched with those regex above.

Not knowing what the formatting of this output here used to be, I wonder if those calls to `printFontInfo(str(fontDict))` shouldn't simply be replaced with something like `print(fontDict.getFontInfo())` (which [FDDict already has](https://github.com/adobe-type-tools/psautohint/blob/master/python/psautohint/fdTools.py#L114), or better yet give `FDDict` a proper `__repr__` method that does what it should here and simply `print(fontDict)`?

Happy to help with this, but need a bit insight as to what this bit of code is expected to return and how.

**Comment by kontur** [comment] 2020-01-14 15:40
Gave it a fix attempt, anyway.

**Comment by josh-hadley** [comment] 2020-01-22 21:59
Thanks for your attempt on this. I agree with your assessment that the empty `return` interferes with the subsequent operations that expect a `fontinfo_list`, and the try-with-silent-pass hides this (and other problems).
I'll have to check in with other folks as to the intended behavior of `--print-dflt-fddict`. It does seem to me like the intent was to simply print and exit. Might be some clues in the now-defunct AFDKO autohint.py program that psautohint was based on. I'll do some research.

**Comment by josh-hadley** [comment] 2020-01-22 22:17
Looks like this option has been broken for a while :-(
At any rate: I went back to an older AFDKO, prior to deprecating the old autohint.py program. From the behavior of that, it definitely looks like the intent with `--print-dflt-fddict` (which was `-pfd` option in autohint.py) was to print then exit.

**Comment by kontur** [comment] 2020-01-27 07:54
Thanks for looking into this more deeply. I have not compared to the formatting and way of exiting to legacy versions, but if it is just a single print of the dftl and then exit I think my PR achieves this; at any rate, it avoids at least exiting with the error :)

**Comment by josh-hadley** [comment] 2020-01-27 23:35
I'd like to try to dig up the history on how this worked and get the output to match. I guess that assumes that it worked at some point in the past 😄  With no existing test cases, hard to say. I'll continue doing some research while awaiting a [release with fix for the remaining CI issue](https://github.com/matthew-brett/multibuild/pull/299) and try to get this wrapped up soon.

**Comment by josh-hadley** [comment] 2020-02-10 19:29
closed by https://github.com/adobe-type-tools/psautohint/pull/225

**Closed by josh-hadley** 2020-02-10 19:29 UTC
